/**
 * 受控 DDL 工具 — 仅限建表，只读模式下禁用
 */
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { getPool, isReadOnly, isDebugMode } from '../db/connection.js';
import { validateIdentifier, escapeIdentifier } from '../db/executor.js';
import { auditLog } from '../audit.js';

export function registerDDLTools(server: McpServer): void {
  server.registerTool(
    'create_table',
    {
      description: 'CREATE TABLE；只读禁',
      inputSchema: {
        table: z.string().describe('表名'),
        columns: z
          .array(
            z.object({
              name: z.string().describe('列名'),
              type: z.string().describe('类型如 INT/VARCHAR(255)'),
              primaryKey: z.boolean().optional().describe('主键'),
              autoIncrement: z.boolean().optional().describe('自增'),
              nullable: z.boolean().optional().describe('可 NULL，默认 true'),
              defaultValue: z.string().optional().describe('DEFAULT 片段'),
              comment: z.string().optional().describe('列注释'),
            })
          )
          .min(1)
          .describe('列定义'),
        comment: z.string().optional().describe('表注释'),
        engine: z.string().optional().describe('兼容参数，PG 忽略'),
        charset: z.string().optional().describe('兼容参数，PG 忽略'),
      },
    },
    async ({ table, columns, comment }, _extra) => {
      if (isReadOnly()) {
        return {
          content: [{ type: 'text', text: '错误：当前处于只读模式，禁止执行 DDL 操作' }],
          isError: true,
        };
      }

      const tableErr = validateIdentifier(table, '表名');
      if (tableErr) {
        return {
          content: [{ type: 'text', text: `错误：${tableErr}` }],
          isError: true,
        };
      }

      for (const col of columns) {
        const colErr = validateIdentifier(col.name, `字段名 ${col.name}`);
        if (colErr) {
          return {
            content: [{ type: 'text', text: `错误：${colErr}` }],
            isError: true,
          };
        }
      }

      const colDefs = columns.map((col) => {
        const parts: string[] = [escapeIdentifier(col.name), col.type];
        if (col.primaryKey) parts.push('PRIMARY KEY');
        if (col.autoIncrement) {
          parts[1] =
            col.type.toLowerCase() === 'bigint'
              ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY'
              : 'INT GENERATED BY DEFAULT AS IDENTITY';
        }
        if (col.nullable === false) parts.push('NOT NULL');
        if (col.defaultValue !== undefined) parts.push(`DEFAULT ${col.defaultValue}`);
        return parts.join(' ');
      });

      const sql = `CREATE TABLE ${escapeIdentifier(table)} (\n  ${colDefs.join(',\n  ')}\n)`;

      const startTime = Date.now();
      try {
        const pool = getPool();
        await pool.query(sql);
        const executionTime = Date.now() - startTime;
        auditLog({ sql, success: true, executionTime });

        const response: Record<string, unknown> = { table, columnsCount: columns.length };
        if (isDebugMode()) response.executionTime = `${executionTime}ms`;
        response.sql = sql;
        if (comment) {
          response.commentWarning =
            'PostgreSQL 版本暂未通过该工具写入表注释，可后续执行 COMMENT ON TABLE';
        }

        return {
          content: [{ type: 'text', text: JSON.stringify(response) }],
        };
      } catch (error) {
        const executionTime = Date.now() - startTime;
        const errorMsg = error instanceof Error ? error.message : '未知错误';
        auditLog({ sql, success: false, error: errorMsg, executionTime });
        return {
          content: [{ type: 'text', text: `建表失败：${errorMsg}` }],
          isError: true,
        };
      }
    }
  );
}
